apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-hostpath-provisioner
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-efs-provisioner
subjects:
  - kind: ServiceAccount
    name: kube-hostpath-provisioner
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:persistent-volume-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-hostpath-provisioner
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: kube-hostpath-provisioner
    spec:
      serviceAccount: kube-hostpath-provisioner
      containers:
        - name: kube-hostpath-provisioner
          image: noonien/kube-hostpath-provisioner:latest
          env:
            - name: KHP_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KHP_ROOT
              value: /media/storage
          volumeMounts:
            - name: pv-volume
              mountPath: /media/storage
      volumes:
        - name: pv-volume
          hostPath:
            path: /media/storage
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: hostpath
provisioner: hostpath.external-storage.incubator.kubernetes.io
